### ISSUE TITLE
Consider supporting arc-swap / working with arc-swap maintainers

### ISSUE THREAD

**Issue by shepmaster** [Storyyeller/stable_deref_trait#12]
Specifically, https://docs.rs/arc-swap/0.4.5/arc_swap/struct.Guard.html. I don't know which crate is best to implement it; hopefully y'all can figure it out 😄

**Comment by Storyyeller** [comment]
My position is that the impls should be done by the create defining the type wherever possible. The only impls provided in this crate are for standard library types.
